export const DUMMY_GUESTLIST = [
  {
    voucherId: "1",
    firstName: "Béla",
    lastName: "Hella",
    nickName: "Beduska",
    email: "bedi@gmail.com",
    phone: null,
    isComing: true,
    didReply: true,
    specialDiet: ["húst hússal", "antivegán"],
    children: [],
    partner: null,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    voucherId: "2",
    firstName: "Zizi",
    lastName: "Buskrafter",
    nickName: "Zizz",
    email: "zizz@hotmail.com",
    phone: "+361234567",
    isComing: true,
    didReply: true,
    specialDiet: [],
    partner: {
      firstName: "Zaza",
      lastName: "Laza",
      nickName: "Zizférj",
      isComing: true,
      specialDiet: [],
    },
    children: [
      {
        firstName: "gyerkőc-1",
        lastName: "Laza",
        nickName: "Zizférj",
        age: 5,
        specialDiet: [],
      },
      {
        firstName: "gyerkőc-2",
        lastName: "Laza",
        nickName: "Zizférj",
        age: 3,
        specialDiet: [],
      },
    ],
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    voucherId: "3",
    firstName: "Erik",
    lastName: "Viking",
    nickName: "Verick",
    email: "erikaviking@citromail.hu",
    isComing: false,
    didReply: true,
    specialDiet: [],
    children: [],
    phone: null,
    partner: null,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    voucherId: "4",
    firstName: "Henrik",
    lastName: "Fingi",
    isComing: false,
    didReply: false,
    specialDiet: [],
    children: [],
    email: null,
    phone: null,
    partner: null,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
];
